"""
Email notification service using SMTP
"""
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional, List
import os
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

class EmailService:
    def __init__(self):
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.email_user = os.getenv("EMAIL_USER")
        self.email_password = os.getenv("EMAIL_PASSWORD")
        self.from_email = os.getenv("FROM_EMAIL", self.email_user)
        
    def is_configured(self) -> bool:
        """Check if email service is properly configured"""
        return bool(self.email_user and self.email_password)
    
    async def send_crash_alert(
        self,
        to_email: str,
        symbol: str,
        current_price: float,
        price_drop: float,
        analysis: str,
        user_name: Optional[str] = None
    ) -> bool:
        """Send crash detection alert email"""
        if not self.is_configured():
            logger.warning("Email service not configured")
            return False
            
        try:
            subject = f"🚨 CRASH ALERT: {symbol} - {price_drop:.2f}% Drop Detected"
            
            # Create HTML email content
            html_content = f"""
            <html>
            <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; text-align: center;">
                    <h1 style="color: white; margin: 0;">🚨 GuardX Crash Alert</h1>
                </div>
                
                <div style="padding: 20px; background-color: #f8f9fa;">
                    <h2 style="color: #dc3545;">Crash Detected: {symbol}</h2>
                    
                    <div style="background: white; padding: 15px; border-radius: 8px; margin: 15px 0;">
                        <h3 style="margin-top: 0; color: #495057;">Alert Details</h3>
                        <p><strong>Symbol:</strong> {symbol}</p>
                        <p><strong>Current Price:</strong> ${current_price:,.4f}</p>
                        <p><strong>Price Drop:</strong> <span style="color: #dc3545; font-weight: bold;">{price_drop:.2f}%</span></p>
                        <p><strong>Detection Time:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
                        {f'<p><strong>User:</strong> {user_name}</p>' if user_name else ''}
                    </div>
                    
                    <div style="background: white; padding: 15px; border-radius: 8px; margin: 15px 0;">
                        <h3 style="margin-top: 0; color: #495057;">AI Analysis</h3>
                        <p style="line-height: 1.6;">{analysis}</p>
                    </div>
                    
                    <div style="background: #e9ecef; padding: 15px; border-radius: 8px; margin: 15px 0;">
                        <h4 style="margin-top: 0; color: #6c757d;">Recommended Actions</h4>
                        <ul style="color: #6c757d;">
                            <li>Review your portfolio exposure to {symbol}</li>
                            <li>Consider risk management strategies</li>
                            <li>Monitor market conditions closely</li>
                            <li>Consult with financial advisors if needed</li>
                        </ul>
                    </div>
                    
                    <div style="text-align: center; margin-top: 20px;">
                        <p style="color: #6c757d; font-size: 12px;">
                            This alert was generated by GuardX AI-powered crash detection system.<br>
                            For more information, visit your dashboard or contact support.
                        </p>
                    </div>
                </div>
            </body>
            </html>
            """
            
            # Create plain text version
            text_content = f"""
            🚨 GUARDX CRASH ALERT 🚨
            
            Symbol: {symbol}
            Current Price: ${current_price:,.4f}
            Price Drop: {price_drop:.2f}%
            Detection Time: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
            {f'User: {user_name}' if user_name else ''}
            
            AI Analysis:
            {analysis}
            
            Recommended Actions:
            - Review your portfolio exposure to {symbol}
            - Consider risk management strategies
            - Monitor market conditions closely
            - Consult with financial advisors if needed
            
            This alert was generated by GuardX AI-powered crash detection system.
            """
            
            return await self._send_email(to_email, subject, text_content, html_content)
            
        except Exception as e:
            logger.error(f"Error sending crash alert email: {e}")
            return False
    
    async def send_monitor_created_notification(
        self,
        to_email: str,
        monitor_name: str,
        symbols: List[str],
        user_name: Optional[str] = None
    ) -> bool:
        """Send notification when a new monitor is created"""
        if not self.is_configured():
            return False
            
        try:
            subject = f"✅ Monitor Created: {monitor_name}"
            
            symbols_list = ", ".join(symbols)
            
            html_content = f"""
            <html>
            <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background: linear-gradient(135deg, #28a745 0%, #20c997 100%); padding: 20px; text-align: center;">
                    <h1 style="color: white; margin: 0;">✅ GuardX Monitor Created</h1>
                </div>
                
                <div style="padding: 20px; background-color: #f8f9fa;">
                    <h2 style="color: #28a745;">Monitor Successfully Created</h2>
                    
                    <div style="background: white; padding: 15px; border-radius: 8px; margin: 15px 0;">
                        <h3 style="margin-top: 0; color: #495057;">Monitor Details</h3>
                        <p><strong>Name:</strong> {monitor_name}</p>
                        <p><strong>Symbols:</strong> {symbols_list}</p>
                        <p><strong>Created:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
                        {f'<p><strong>User:</strong> {user_name}</p>' if user_name else ''}
                    </div>
                    
                    <div style="background: #d4edda; padding: 15px; border-radius: 8px; margin: 15px 0; border-left: 4px solid #28a745;">
                        <h4 style="margin-top: 0; color: #155724;">What's Next?</h4>
                        <ul style="color: #155724;">
                            <li>Your monitor is now actively tracking the specified symbols</li>
                            <li>You'll receive alerts when crash conditions are detected</li>
                            <li>AI analysis will be provided with each alert</li>
                            <li>You can manage your monitors through the dashboard</li>
                        </ul>
                    </div>
                    
                    <div style="text-align: center; margin-top: 20px;">
                        <p style="color: #6c757d; font-size: 12px;">
                            GuardX is now monitoring your selected cryptocurrencies 24/7.<br>
                            Stay protected with AI-powered crash detection.
                        </p>
                    </div>
                </div>
            </body>
            </html>
            """
            
            text_content = f"""
            ✅ GUARDX MONITOR CREATED
            
            Monitor Name: {monitor_name}
            Symbols: {symbols_list}
            Created: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
            {f'User: {user_name}' if user_name else ''}
            
            What's Next?
            - Your monitor is now actively tracking the specified symbols
            - You'll receive alerts when crash conditions are detected
            - AI analysis will be provided with each alert
            - You can manage your monitors through the dashboard
            
            GuardX is now monitoring your selected cryptocurrencies 24/7.
            """
            
            return await self._send_email(to_email, subject, text_content, html_content)
            
        except Exception as e:
            logger.error(f"Error sending monitor created notification: {e}")
            return False
    
    async def _send_email(
        self,
        to_email: str,
        subject: str,
        text_content: str,
        html_content: Optional[str] = None
    ) -> bool:
        """Send email using SMTP"""
        try:
            # Create message
            message = MIMEMultipart("alternative")
            message["Subject"] = subject
            message["From"] = self.from_email
            message["To"] = to_email
            
            # Add text part
            text_part = MIMEText(text_content, "plain")
            message.attach(text_part)
            
            # Add HTML part if provided
            if html_content:
                html_part = MIMEText(html_content, "html")
                message.attach(html_part)
            
            # Create secure connection and send email
            context = ssl.create_default_context()
            
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls(context=context)
                server.login(self.email_user, self.email_password)
                server.sendmail(self.from_email, to_email, message.as_string())
            
            logger.info(f"Email sent successfully to {to_email}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send email to {to_email}: {e}")
            return False

# Global email service instance
email_service = EmailService()